FROM node:20-alpine

RUN apk add --no-cache git

RUN git clone https://github.com/TorrenceB/mental-health-fe.git /app

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]
