FROM node:20-alpine

RUN apk add --no-cache git

RUN git clone https://github.com/TorrenceB/mental-health-fe.git /app/frontend

WORKDIR /app/frontend

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
