services:
 frontend-dev:
  container_name: dev
  image: mcr.microsoft.com/devcontainers/typescript-node
  volumes:
   - ..:/workspace:cached
  ports:
   - "3000:3000"
  environment:
   - CHOKIDAR_USEPOLLING=true
   - WATCHPACK_POLLING=true
   - NEXT_WEBPACK_USEPOLLING=1
  restart: always
  command: npm run dev
