version: "3.8"
services:
 mental-health-app-dev:
  container_name: mental-health-app-dev
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - ./:/app
   - /app/node_modules
  ports:
   - "3000:3000"
  environment:
   - CHOKIDAR_USEPOLLING=true
   - WATCHPACK_POLLING=true
  restart: always
  command: npm start
