services:
 fe-dev:
  container_name: fe-dev
  image: mcr.microsoft.com/devcontainers/typescript-node
  volumes:
   - .:/app:cached
   - /app/node_modules
  ports:
   - "3000:3000"
  environment:
   - CHOKIDAR_USEPOLLING=true
   - WATCHPACK_POLLING=true
   - NEXT_WEBPACK_USEPOLLING=1
  restart: always
  command: npm run dev
