version: "3.8"
services:
 dev:
  container_name: dev
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - ./:/app
   - /app/node_modules
   - /app/.next
  ports:
   - "3000:3000"
  environment:
   - CHOKIDAR_USEPOLLING=true
   - WATCHPACK_POLLING=true
   - NEXT_WEBPACK_USEPOLLING=1
  restart: always
  command: npm run dev
